spring.application.name=trackinvest

spring.datasource.url=jdbc:postgresql://localhost:5432/TrackInvest
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Configuración de AWS Cognito
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_rVxTSYl8Q/.well-known/jwks.json
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://cognito-idp.us-east-1.amazonaws.com/us-east-1_rVxTSYl8Q
spring.security.oauth2.resourceserver.jwt.clientId=2b87qbi8mntusvm96clm10o41u
spring.security.oauth2.resourceserver.jwt.clientSecret=c4hm0k99lr1k0e6b84on1vbsa9727qvi42c1qterqq5qn340v2e
auth.cognitoUri=https://us-east-1rvxtsyl8q.auth.us-east-1.amazoncognito.com