spring.application.name=trackinvest

spring.datasource.url=jdbc:postgresql://localhost:5432/tracInvest
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

security.jwt.key.private=9a4f686c59d5b0d7dbd3c74c8b367b812f846d03a1820e1d73c778f970bc4a5a
security.jwt.user.generator=TrackInvest