apiVersion: v1
kind: ConfigMap
metadata:
  name: account-service-config
  namespace: trackinvest
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres:5432/TrackInvest"
  SPRING_DATASOURCE_USERNAME: "postgres"
  RABBITMQ_HOST: "rabbitmq"
  RABBITMQ_PORT: "5672"
  RABBITMQ_USER: "guest"
