apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: trackinvest

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres-pvc.yaml
  - postgres-service.yaml
  - rabbitmq-deployment.yaml
  - rabbitmq-service.yaml
  - app-deployment.yaml
  - app-service.yaml
