apiVersion: v1
kind: Secret
metadata:
  name: account-service-secrets
  namespace: trackinvest
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "your-db-password"
  RABBITMQ_PASSWORD: "your-rabbitmq-password"
  COGNITO_JWK_SET_URI: "https://cognito-idp.REGION.amazonaws.com/POOL_ID/.well-known/jwks.json"
  COGNITO_ISSUER_URI: "https://cognito-idp.REGION.amazonaws.com/POOL_ID"
  COGNITO_CLIENT_ID: "your-client-id"
  COGNITO_CLIENT_SECRET: "your-client-secret"
  COGNITO_URI: "https://DOMAIN.auth.REGION.amazoncognito.com"
