name: Advanced CI with SonarCloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, master, develop ]

# Forzar los permisos correctos de identidad para evitar fallos de seguridad (403 Forbidden)
permissions:
  id-token: write
  contents: read
  pull-requests: write

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: TrackInvest
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Clave para que SonarCloud pueda analizar el historial de Git

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      # Cachear los paquetes de SonarCloud para que el pipeline corra más rápido en los siguientes push
      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # Compila, corre tests, JaCoCo genera el reporte y Maven se lo envía a SonarCloud
      - name: Build, Test and Analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Lo provee GitHub automáticamente
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Mantener como variable por si el plugin la busca de fondo

          COGNITO_JWK_SET_URI: ${{ secrets.COGNITO_JWK_SET_URI }}
          COGNITO_ISSUER_URI: ${{ secrets.COGNITO_ISSUER_URI }}
          COGNITO_CLIENT_ID: ${{ secrets.COGNITO_CLIENT_ID }}
          COGNITO_CLIENT_SECRET: ${{ secrets.COGNITO_CLIENT_SECRET }}
          COGNITO_URI: ${{ secrets.COGNITO_URI }}
        run: |
          ./mvnw clean verify org.sonarsource.scanner.maven:sonar-maven-plugin:5.7.0.6970:sonar \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.organization=diegoaarm \
            -Dsonar.projectKey=DiegoaARM_trackinvest-account-service \
            -Dsonar.host.url=https://sonarcloud.io